FROM subspacelabs/ubuntu:arm64v8

ENV \
    GETH_RELEASE=1.8.22-7fa3509e \
    GETH_ARCH=arm64 \
    GETH_MD5=16d01d83164a1b320f9b65e038eb0c7d

COPY docker/build.sh /build.sh
COPY docker/entrypoint.sh /entrypoint.sh

RUN ["/build.sh"]

EXPOSE 8545 8546

ENTRYPOINT ["/entrypoint.sh"]
